### ISSUE TITLE
In the context of having a private repository protected by authentication and credentials, what is a SecretStore?

### ISSUE THREAD

**Issue by Darian-FRB** [MicrosoftDocs/PowerShell-Docs-PSGet#128]
### Type of issue

Missing information

### Feedback

My organization maintains private repositories protected by credentials. The documentation references, in bold, **SecretStore**. This is a generic term whose definition varies.

It is not clear if a PowerShell credential object is supported, [Creating credential object](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/add-credentials-to-powershell-functions?view=powershell-7.4#creating-credential-object), or if the [](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.secretstore/?view=ps-modules)/[](https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretStore) module is required.

If the module is required, it is concerning that:

_This module is supported under traditional Microsoft support agreements, including [paid support](https://support.microsoft.com/hub/4343728/support-for-business), [Microsoft Enterprise Agreements](https://www.microsoft.com/licensing/licensing-programs/enterprise?rtc=1&activetab=enterprise-tab%3aprimaryr2), and [Microsoft Software Assurance](https://www.microsoft.com/licensing/licensing-programs/software-assurance-default.aspx). You can also pay for [support](https://support.microsoft.com/contactus) for PowerShell by filing a support request for your problem. Please file issues in the source repository using the This product button in the Feedback section at the bottom of the page._

### Page URL

https://learn.microsoft.com/en-us/powershell/gallery/powershellget/how-to/credential-persistence?view=powershellget-3.x

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/blob/main/powershell-gallery/docs-conceptual/powershellget/how-to/credential-persistence.md

### Author

@sdwheeler

### Document Id

2af43a73-f1b0-8080-5a70-60b5f51e5ba3

**Comment by michaeltlombardi** [comment]
A few notes:

- In our documentation, the bolded **SecretStore** references the [SecretStore module][01].
- The [`Register-PSResourceRepository`][02] cmdlet expects a **Microsoft.PowerShell.PSResourceGet.UtilClasses.PSCredentialInfo** object for the `-CredentialInfo` parameter, not a **PSCredential** object.

Regarding whether the **SecretStore** module is required, a note in the prerequisites section of the article clarifies:

> This example uses **SecretStore**, but you can use any **SecretManagement** extension vault and with any repository.

There are [severable available extension vaults][03], including [Azure KeyVault][04], that you can use instead of a **SecretStore** vault. 

[01]: https://learn.microsoft.com/powershell/utility-modules/secretmanagement/get-started/using-secretstore?view=ps-modules
[02]: https://learn.microsoft.com/powershell/module/microsoft.powershell.psresourceget/register-psresourcerepository?view=powershellget-3.x
[03]: https://learn.microsoft.com/powershell/utility-modules/secretmanagement/overview?view=ps-modules#discovering-and-installing-vault-extensions
[04]: https://learn.microsoft.com/powershell/utility-modules/secretmanagement/how-to/using-azure-keyvault?view=ps-modules
